server:
  tomcat:
    uri-encoding: utf-8

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  devtools:
    restart:
      poll-interval: 4s

  redis:
    host: localhost
    port: 6379
    password: KSNwJwcOUj2KBLJQ

  datasource:
    url: jdbc:mysql://localhost:3306/db_0?charset=utf-8&useSSL=true
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.codve.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
