spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_0?charset=utf-8&useSSL=true
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.codve.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
